### ISSUE TITLE
Preliminary work for spin-off of Upplication/Amazon-S3-FileSystem-NIO2

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio2#1]
# Task Description

This is the master task for creating a spin-off of [Upplication/Amazon-S3-FileSystem-NIO2].

# Tasks

* [ ] Contact the original authors.
  * Reached out to @martint who created [martint/s3fs] on which [Upplication/Amazon-S3-FileSystem-NIO2] is based. Martin Traverso has confirmed he is happy to have the project under both an Apache 2.0 and MIT license, as well as for someone else to continue the work on this; (his original project is under an [Apache 2.0 license](https://github.com/martint/s3fs/blob/master/pom.xml#L13)).
  * Reached out to @jarnaiz who forked [martint/s3fs] and further developed it as [Upplication/Amazon-S3-FileSystem-NIO2]. The fork appears as being under an [MIT license](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/blob/master/LICENSE), but the `pom.xml` file states it is (only) under an [`Apache 2.0`](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/blob/master/pom.xml#L13). As @jarnaiz has not replied, and, since it isn't perfectly unclear under which of the two licenses the project is, our spin-off will be dual-licensed.
* [ ] Add licenses:
  * [ ] Update the `pom.xml`.
  * [ ] Add license files for both licenses.
* [ ] Re-indent code accoring to the Carlspring style.
* [ ] Refactor package names to use `org.carlspring.cloud.storage.s3fs`.
* [ ] Set the `maven-enforcer-plugin` to require Maven `3.6.3`.
* [ ] Update all Maven dependencies to their latest versions.
* [ ] Update all Maven plugins to their latest versions.
* [ ] Upgrade to the latest `aws-java-sdk-s3`.
* [ ] Replace `log4j` with `slf4j`.
* [ ] Remove all unnecessary `throws` in method definitions.
* [ ] Migrate to JUnit 5.x.
* [ ] Set up issue templates.
* [ ] Set up pull request templates.
* [ ] Set up project labels.
* [ ] Set up Github Actions.
* [ ] Set up GitGuardian.
* [ ] Set up Sonarcloud analysis.
* [ ] Set up Snyk.io.
* [ ] Set up badges.
* [ ] Inform people who might be interested about the project
  * [ ] Reach out to all of the contributors who:
    * [ ] Raised issues on [Upplication/Amazon-S3-FileSystem-NIO2] (which are still open).
    * [ ] Raised pull requests on [Upplication/Amazon-S3-FileSystem-NIO2] (which are still unmerged).
    * [ ] Created forks of [Upplication/Amazon-S3-FileSystem-NIO2] in order to fix bits and pieces.
  * [ ] Reach out to the folks at [aws-sdk-java-v2] 

[martint/s3fs]: https://github.com/martint/s3fs
[Upplication/Amazon-S3-FileSystem-NIO2]: https://github.com/Upplication/Amazon-S3-FileSystem-NIO2
[aws-sdk-java-v2]: https://github.com/aws/aws-sdk-java-v2

**Comment by oeph** [comment]
Is there any ETA for this? I'm highly interested in this library

**Comment by carlspring** [comment]
@oeph ,

Thank you for your interest!

We were hoping to have a version released by the end of the month (January/2021), but this has turned out to be a very busy January for me. It's mainly @ptirador and myself working on this project at the moment and we would be more than happy to get an extra helping hand, if you're up for it! :)

There are still a few important things that we would like to do before we cut a release. I've been busy re-working some code which will make things a lot easier to work with. We also have several follow-up tasks related to the migration from Amazon SDK v1 to v2 that are still outstanding and which we would like to have as part of `1.0.0`.

Apart from this, we need to improve the site-based documentation. I have prepared a Spring-based "Hello, World!" (and we will need a few more example projects) but I would rather not push any of this before having finished the above-mentioned refactoring.

And, in addition to this, it appears that this Github repository will have to be moved into a Github Organization of its own so that we could have teams and other extras.

I estimate all this to take another month, or month an a half. This project is alive and kicking and is a priority for us. However, there is only so much one can do, with a daytime job as well. In the meantime, please, feel free to build it locally and try it out. Let us know, if you find any bugs, or have ideas for improvements. Pull requests are also more than welcome! :)

If you would like to help out, please get in touch with us and join [our chat channel](https://chat.carlspring.org/channel/s3fs-nio-community).

**Comment by carlspring** [comment]
@oeph ,

Thanks for your interest! We have now released version [1.0.0](https://github.com/carlspring/s3fs-nio/releases/tag/v1.0.0) to Maven Central (https://repo.maven.apache.org/maven2/).
