### ISSUE TITLE
Migrate to JUnit 5.x

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio2#12]
# Task Description

The project is still using JUnit 4.x. We should make the necessary code changes to migrate to JUnit 5 (Jupiter).

# Tasks

* [x] Upgrade to JUnit 5.x.
* [x] Make the necessary code changes.
* [x] Make sure there are no legacy dependencies.
