### ISSUE TITLE
Change the licenses

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio2#2]
# Task Description

We should define the project's licensing terms.

# Tasks

* [ ] Contact the original authors.
  * Reached out to @martint who created [martint/s3fs] on which [Upplication/Amazon-S3-FileSystem-NIO2] is based. Martin Traverso has confirmed he is happy to have the project under both an Apache 2.0 and MIT license, as well as for someone else to continue the work on this; (his original project is under an [Apache 2.0 license](https://github.com/martint/s3fs/blob/master/pom.xml#L13)).
  * Reached out to @jarnaiz who forked [martint/s3fs] and further developed it as [Upplication/Amazon-S3-FileSystem-NIO2]. The fork appears as being under an [MIT license](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/blob/master/LICENSE), but the `pom.xml` file states it is (only) under an [`Apache 2.0`](https://github.com/Upplication/Amazon-S3-FileSystem-NIO2/blob/master/pom.xml#L13). As @jarnaiz has not replied, and, since it isn't perfectly unclear under which of the two licenses the project is, our spin-off will be dual-licensed.
* [ ] Add licenses:
  * [ ] Update the `pom.xml`.
  * [ ] Add license files for both licenses.
