### ISSUE TITLE
Get code coverage working in Sonarcloud using JaCoCo

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio2#58]
# Task Description

Currently, we're not collecting any code coverage, as this has been commented out.

# Tasks

The following tasks will need to be carried out:
* [x] Create a new Maven profile for the code coverage.
* [x] Upgrade the `jacoco-maven-plugin` to the latest.
* [x] Apply the necessary fixes to get things working.
* [x] Make things work through the Github Action.

# Task Relationships

This task:
* Is a sub-task of: #
* Depends on: #
* Is a follow-up of: #
* Relates to: #59 

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio2-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov
