### ISSUE TITLE
Fix the failing integration tests

### ISSUE THREAD

**Issue by carlspring** [carlspring/s3fs-nio2#59]
# Task Description

We need to sort out the failing integration tests.

To run the build with the integration tests enabled, run:
```
mvn clean package -Pintegration-tests
```

# Tasks

The following tasks will need to be carried out:
* [ ] Check if these were ever working in the `master` of [Amazon-S3-FileSystem-NIO2].
* [ ] Check if these were fixed in any of the forks.
* [ ] Apply the necessary fixes.

# Help

* Our [chat channel](https://chat.carlspring.org/channel/s3fs-nio2-community)
* Points of contact:
  * @carlspring
  * @steve-todorov
  * @sbespalov

[Amazon-S3-FileSystem-NIO2]: https://github.com/Upplication/Amazon-S3-FileSystem-NIO2

**Comment by carlspring** [comment]
The last successful Travis build: [382704834](https://travis-ci.org/github/Upplication/Amazon-S3-FileSystem-NIO2/jobs/382704834).
